/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package janelas;

import java.util.ArrayList;
import javax.swing.JList;
import classes.Componente;
import classes.Placa;

/**
 *
 * @author Rafa
 */
public class JanelaListaComponentes extends javax.swing.JFrame {

    /**
     * Creates new form JanelaListaComponentes
     */
    private ArrayList<Componente> componentes;
    private ArrayList<Componente> componenteBusca;
    private String[] nomesComponentes;

    public JanelaListaComponentes(ArrayList<Componente> componentes) {
        this.componentes = componentes;

        this.nomesComponentes = new String[componentes.size()];
        for (int i = 0; i < componentes.size(); i++) {
            this.nomesComponentes[i] = componentes.get(i).getNome();
        }
        this.sortStringBubble(nomesComponentes);
        initComponents();
        this.jLabelTotal.setText(Integer.toString(this.componentes.size()));
        this.setVisible(true);
    }

    private void sortStringBubble(String x[]) { // ARRUMAR BUG ARRAYLIST
        int j;
        boolean flag = true;
        String aux;
        Componente componente;
        while (flag) {
            flag = false;
            for (j = 0; j < x.length - 1; j++) {
                if (x[j].compareToIgnoreCase(x[j + 1]) > 0) {
                    aux = x[j];
                    componente = this.componentes.get(j);
                    x[j] = x[j + 1];
                    this.componentes.set(j, this.componentes.get(j + 1));
                    x[j + 1] = aux;
                    this.componentes.set(j + 1, componente);
                    flag = true;
                }
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        listaComponentes = new javax.swing.JList<>();
        jButtonBuscarNome = new javax.swing.JButton();
        jTextFieldNome = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jListBusca = new javax.swing.JList<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabelTotal = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        this.listaComponentes  = new JList(this.nomesComponentes);
        listaComponentes.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        listaComponentes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listaComponentesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(listaComponentes);
        listaComponentes.getAccessibleContext().setAccessibleName("");

        jButtonBuscarNome.setText("Buscar");
        jButtonBuscarNome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonBuscarNomeMouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel1.setText("Buscar por nome");

        jListBusca.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        this.jListBusca.setVisible(false);
        jListBusca.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jListBuscaMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jListBusca);

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel2.setText("Componentes");

        jLabel3.setText("Total de Componentes: ");

        jLabelTotal.setText("X");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(91, 91, 91)
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldNome, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonBuscarNome))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(178, 178, 178)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelTotal)))
                .addContainerGap(126, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)
                            .addComponent(jButtonBuscarNome))
                        .addGap(55, 55, 55)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 403, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabelTotal))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void listaComponentesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listaComponentesMouseClicked
        System.out.println(this.componentes.get(this.listaComponentes.getAnchorSelectionIndex()).getDescricao());
        JanelaComponenteInfo componentInfo;
        JanelaPlacaInfo placaInfo;
        if(this.componentes.get(this.listaComponentes.getAnchorSelectionIndex()) instanceof Placa)
            placaInfo = new JanelaPlacaInfo((Placa)this.componentes.get(this.listaComponentes.getAnchorSelectionIndex()));
        else            
            componentInfo = new JanelaComponenteInfo(this.componentes.get(this.listaComponentes.getAnchorSelectionIndex()));
        
            
    }//GEN-LAST:event_listaComponentesMouseClicked

    private void jButtonBuscarNomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonBuscarNomeMouseClicked

        ArrayList<String> listastr = new ArrayList();
        this.componenteBusca = new ArrayList();
        for (Componente a : this.componentes) {
            if (a.getNome().contains(this.jTextFieldNome.getText())) {
                listastr.add(a.getNome());
                this.componenteBusca.add(a);
            }
        }
        String[] nomes = listastr.toArray(new String[listastr.size()]);
        this.jListBusca.setModel(new javax.swing.AbstractListModel<String>() {
            public int getSize() {
                return nomes.length;
            }

            public String getElementAt(int i) {
                return nomes[i];
            }
        });
        this.jListBusca.setVisible(true);
    }//GEN-LAST:event_jButtonBuscarNomeMouseClicked

    private void jListBuscaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jListBuscaMouseClicked
        // Seleciona aluno na lista e abre janela com informações sobre o aluno cadastrado.
        System.out.println(this.listaComponentes.getAnchorSelectionIndex());
//        JanelaComponenteInfo alunoInfo = new JanelaComponenteInfo(this.componenteBusca.get(this.jListBusca.getAnchorSelectionIndex()));
//        alunoInfo.mostraJanela();
    }//GEN-LAST:event_jListBuscaMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBuscarNome;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelTotal;
    private javax.swing.JList<String> jListBusca;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextFieldNome;
    private javax.swing.JList<String> listaComponentes;
    // End of variables declaration//GEN-END:variables

}
